name = "Infernal"
uuid = "4aa08641-d763-4623-9c5b-cef742500064"
authors = ["Andrea Di Gioacchino", "JFdCD <jfdecd@icloud.com>"]
version = "1.4.2-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GSL_jll = "1b77fbbe-d8ee-58f0-85f9-836ddc23a7a4"
Infernal_jll = "5109d7c4-8f61-540a-bdd6-fb9d06080a8f"

[compat]
CSV = "0.10.4"
DataFrames = "1.3.6"
GSL_jll = "~2.7"
Infernal_jll = "1.1.5"
julia = "1.8"
